// react/src/pages/form/advancedForm.js
import React, { memo,useState,useEffect } from 'react'
import PageLayout from '@/layouts/pageLayout'
import { Button, Modal, Form, Input,Radio ,Divider,InputNumber,DatePicker,Row,Col,Space } from 'antd';
import Inputs from '@/components/input';
import Select from '@/components/select'
import { langeList } from '@/assets/js/staticData'
import { DeleteOutlined } from '@ant-design/icons';
import TimeRangeSelection from '@/components/timeRangeSelection'
import moment from 'moment';

const AdvancedForm = memo(function AdvancedForm(props) {

  const initValue = [{names:'',sex:'',address:'',school:'',age:'',birth:''}];

  const [stepList,setStepList] = useState(initValue);

  const [addNumber,setAddNumber]=useState(0);

  const [form] = Form.useForm();

  useEffect(() => { // 默认值
    const userInfoList = [
      {names:'帅峰峰',sex:1,address:'北京海定区',school:'北京技术技术大学',age:24,birth:moment('2015-01-01')}
    ]
    setStepList(userInfoList);
    form.setFieldsValue({userInfoList,lang:2});
  }, [])

  const  mapRender=(data)=>{
    return (
        data.map((item,index)=>(
          <div key={index}>
               <Divider>信息{index+1}</Divider>
                <div>
                    {
                      index>0 &&  <Button type="danger" onClick={()=>removeStemp(index)} shape="circle" icon={<DeleteOutlined style={{color:'#fff'}}/>} className='fr' style={{marginLeft:'20px'}}/>
                    }
                </div>
                <Form.Item label='名字' labelAlign='left'  name={["userInfoList", index, "names"]}  rules={[{required: true, message: '请填写描述!' }]}>
                  <Inputs/>
                </Form.Item>
                <Form.Item label='性别' labelAlign='left'  name={["userInfoList", index, "sex"]}  rules={[{required: true, message: '请填写描述!' }]}>
                  <Radio.Group>
                    <Radio value={1}>男</Radio>
                    <Radio value={2}>女</Radio>
                  </Radio.Group>
                </Form.Item>
                <Form.Item label='地址' labelAlign='left'  name={["userInfoList", index, "address"]}  rules={[{required: true, message: '请填写描述!' }]}>
                  <Inputs/>
                </Form.Item>
                <Form.Item label='学校' labelAlign='left'  name={["userInfoList", index, "school"]}  rules={[{required: true, message: '请填写描述!' }]}>
                  <Inputs/>
                </Form.Item>
                <Form.Item label='年龄' labelAlign='left'  name={["userInfoList", index, "age"]}  rules={[{required: true, message: '请填写描述!' }]}>
                  <InputNumber />
                </Form.Item>
                <Form.Item label='出生日期' labelAlign='left'  name={["userInfoList", index, "birth"]}  rules={[{required: true, message: '请填写描述!' }]}>
                   <DatePicker />
                </Form.Item>
           </div>
        ))
    )
  }

  const addStemp =()=> {
    setAddNumber(addNumber+1);
    setStepList([...stepList,...initValue]);
  };

  const removeStemp = (k) => {  // 删除
    setStepList(stepList.filter((item,index) =>index !== k));
    const userInfoList =form.getFieldValue('userInfoList');
    form.setFieldsValue({ // 对删除的值进行匹配
      userInfoList: userInfoList.filter((item,index) => index !== k),
    });
  }

  const  handleSubmit = e => {
    form.validateFields().then(values => {
      const data = values;
      data.userInfoList.forEach(item=>{
        item.birth = item.birth.format('YYYY-MM-DD');
      })
      alert(JSON.stringify(data))
    })
  }

  return (
    <PageLayout>
      <Row gutter={[10, 10]}>
        <Col xs={24} sm={24} md={12} lg={8} xl={8}>
          <Form form={form}>
            <Form.Item label="平台" name='platform'>
              <Inputs/>
            </Form.Item>
            <Form.Item label="语言" name='lang'>
              <Select data={langeList} valName='label' valKey='value' />
            </Form.Item>
            <Form.Item label="时间" name="times">
              <TimeRangeSelection />
            </Form.Item>
            <Form.Item>
              {mapRender(stepList)}
            </Form.Item>
          </Form>
       </Col>
       <Col xs={24} sm={24} md={12} lg={16} xl={16}>
         <div style={{height:'100%',borderLeft:'1px solid #f0f0f0',paddingLeft:'20px',marginLeft:'20px',display:'flex',alignItems:'center'}}>
            <Space>
              <Button type="primary" danger onClick={addStemp}>新增信息</Button>
              <Button type="primary" onClick={handleSubmit}>提交信息</Button>
            </Space>
         </div>
       </Col>
      </Row>
    </PageLayout>
  )
})

export default AdvancedForm

// vue+typescript/src/views/form/advanced-form.vue
<template>
  <div class="com-page p20">
    <a-form class="form" :model="form" :rules="rules" label-align="left" @finish="onFinish">
      <a-row :gutter="[10, 20]" type="flex">
        <a-col :xs="24" :sm="24" :md="12" :lg="8" :xl="8">
          <a-form-item label="平台" name="platform">
            <a-input v-model:value="form.platform" placeholder="请填写" />
          </a-form-item>
          <a-form-item label="语言" name="lang">
            <a-select v-model:value="form.lang">
              <a-select-option v-for="item in langeList" :key="item.value" :value="item.value">
                {{ item.label }}
              </a-select-option>
            </a-select>
          </a-form-item>
          <a-form-item label="时间" name="times">
            <TimeRangeSelection v-model:value="form.times"></TimeRangeSelection>
          </a-form-item>
          <transition-group name="list">
            <div v-for="(item, index) in form.userInfoList" :key="index" class="item">
              <a-divider>信息{{ index + 1 }}</a-divider>
              <div v-show="index > 0">
                <a-button class="button--delete" type="danger" shape="circle" @click="onRemoveStep(index)">
                  <template #icon><DeleteOutlined /></template>
                </a-button>
              </div>
              <a-form-item
                label="名字"
                :name="['userInfoList', index, 'names']"
                :rules="[{ required: true, message: '请填写描述!' }]"
              >
                <a-input v-model:value="item.names" placeholder="请填写" />
              </a-form-item>
              <a-form-item
                label="性别"
                :name="['userInfoList', index, 'sex']"
                :rules="[{ required: true, message: '请选择性别!' }]"
              >
                <a-radio-group v-model:value="item.sex">
                  <a-radio :value="1">男</a-radio>
                  <a-radio :value="2">女</a-radio>
                </a-radio-group>
              </a-form-item>
              <a-form-item
                label="地址"
                :name="['userInfoList', index, 'address']"
                :rules="[{ required: true, message: '请填写地址!' }]"
              >
                <a-input v-model:value="item.address" placeholder="请填写" />
              </a-form-item>
              <a-form-item
                label="学校"
                :name="['userInfoList', index, 'school']"
                :rules="[{ required: true, message: '请填写学校!' }]"
              >
                <a-input v-model:value="item.school" placeholder="请填写" />
              </a-form-item>
              <a-form-item
                label="年龄"
                :name="['userInfoList', index, 'age']"
                :rules="[{ required: true, message: '请填写年龄!' }]"
              >
                <a-input-number v-model:value="item.age" placeholder="请填写" />
              </a-form-item>
              <a-form-item
                label="出生日期"
                :name="['userInfoList', index, 'birth']"
                :rules="[{ required: true, message: '请填写出生日期!' }]"
              >
                <a-date-picker v-model:value="item.birth" />
              </a-form-item>
            </div>
          </transition-group>
          <a-form-item>
            <a-row type="flex" align="middle" class="button-group">
              <a-button type="danger" class="mr8" @click="onAddStep"> 新增信息 </a-button>
              <a-button type="primary" html-type="submit">提交信息</a-button>
            </a-row>
          </a-form-item>
        </a-col>
        <a-col :xs="24" :sm="24" :md="12" :lg="16" :xl="16">
          <a-row type="flex" align="middle" class="button-group">
            <a-button type="danger" class="mr8" @click="onAddStep"> 新增信息 </a-button>
            <a-button type="primary" html-type="submit">提交信息</a-button>
          </a-row>
        </a-col>
      </a-row>
    </a-form>
  </div>
</template>

<script lang="ts">
import { defineComponent, reactive } from 'vue'
import { DeleteOutlined } from '@ant-design/icons-vue'
import TimeRangeSelection from '@/components/time-range-selection/index.vue'
import moment from 'moment'
import { enumLangList } from '@/utils/enum'

type UserInfoItemType = {
  names: string
  sex: number
  address: string
  school: string
  age: number
  birth: moment.Moment | null
}

function genUserInfoItem(): UserInfoItemType {
  return {
    names: '',
    sex: 1,
    address: '',
    school: '',
    age: 24,
    birth: null
  }
}
export default defineComponent({
  components: {
    TimeRangeSelection,
    DeleteOutlined
  },
  setup() {
    const form = reactive({
      platform: '',
      lang: 2,
      times: [],
      userInfoList: [
        {
          names: '帅峰峰',
          sex: 1,
          address: '北京海定区',
          school: '北京技术技术大学',
          age: 24,
          birth: moment('2015-01-01')
        }
      ] as UserInfoItemType[]
    })
    const rules = reactive({})

    const langeList = reactive(enumLangList)

    function onAddStep() {
      form.userInfoList.push(genUserInfoItem())
    }
    function onRemoveStep(index: number) {
      form.userInfoList.splice(index, 1)
    }
    function onFinish() {
      const userInfoList = form.userInfoList.map(item => {
        const birth = item.birth?.format('YYYY-MM-DD')
        return Object.assign({}, item, {
          birth
        })
      })
      const ret = Object.assign({}, form, {
        userInfoList
      })
      alert(JSON.stringify(ret, null, 2))
    }
    return {
      form,
      rules,
      langeList,
      onAddStep,
      onFinish,
      onRemoveStep
    }
  }
})
</script>

<style lang="less" scoped>
.form {
  ::v-deep(.ant-form-item) {
    display: flex;
  }

  ::v-deep(.ant-form-item-control-wrapper) {
    flex: 1;
  }
}

.button-group {
  height: 100%;
  border-left: 1px solid #f0f0f0;
  padding-left: 20px;
  margin-left: 20px;
}

.item {
  position: relative;
}

.button--delete {
  float: right;
  margin-left: 20px;
}

.list-enter-active,
.list-leave-active {
  transition: all 0.3s;
}

.list-enter-from,
.list-leave-to {
  opacity: 0;
  transform: translateY(30px);
}
</style>
