// react/src/pages/form/tableForm.js
import React, { memo } from 'react'
import PageLayout from '@/layouts/pageLayout'
import { Form , Row, Col, InputNumber,Button,Image } from 'antd';
import TimeRangeSelection from '@/components/timeRangeSelection'
import { langeList } from '@/assets/js/staticData'
import Inputs from '@/components/input';
import Select from '@/components/select'
import Table from '@/components/table'

const TableForm = memo(function TableForm(props) {

  const [form] = Form.useForm();

  const staticData = [
    {
      productId:'odde43-de',
      pictureurls:'https://antd-simple-pro.oss-cn-beijing.aliyuncs.com/image/1616494356149.png',
      productNumber:0,
      firstJourneyExpenses:0,
      remarks:'今天天气真好'
    },
    {
      productId:'odde41-de',
      pictureurls:'https://antd-simple-pro.oss-cn-beijing.aliyuncs.com/image/1616494473689.jpg',
      productNumber:0,
      firstJourneyExpenses:0,
      remarks:'你真的好漂亮呀'
    },
  ];

  const columns = [
    {
      key: 'index',
      align: 'center',
      title: '序号',
      width:200,
      render: (text, record, index) => `${index + 1}`,
    },
    {
      align: 'center',
      title: '图片',
      dataIndex: 'pictureurls',
      render: (text) => (
        <>
          {text.length ? <Image src={text} alt="头像" style={{ cursor: 'pointer' }} width={50} height={50} /> : null}
        </>
      ),
      key:'pictureurls',
    },
    {
      align: 'center',
      title: '数量',
      dataIndex: 'productNumber',
      key: 'productNumber',
      editable: true,
    },
    {
      align: 'center',
      title: '购买量',
      dataIndex: 'firstJourneyExpenses',
      key: 'firstJourneyExpenses',
      editable: true,
    },
    {
      align: 'center',
      title: '备注',
      dataIndex: 'remarks',
      key: 'remarks',
    }
  ];

    // 动态编辑table
    const EditableCell = ({
      editing,
      dataIndex,
      title,
      inputType,
      record,
      index,
      children,
      ...restProps
    }) => {
      return (
        <td {...restProps}>
          {editing ? (
            <Form.Item
              name={['all',record.productId,dataIndex]}
              rules={[
                {
                  required: true,
                  message: `请填写!`,
                },
              ]}
            >
              <InputNumber min={0}/>
            </Form.Item>
          ) : (
            children
          )}
        </td>
      );
    };

    const mergedColumns =columns.map((col) => {
      if (!col.editable) {
        return col;
      }
      return {
        ...col,
        onCell: (record) => ({
          record,
          inputType:'text',
          dataIndex: col.dataIndex,
          title: col.title,
          editing: true,
        }),
      };
    });

  const datas = {
    tableProps: {
      id:'productId',
      columns:mergedColumns,
      dataSource:staticData,
      rowClassName:"editable-row",
      components:{
        body: {
          cell: EditableCell,
        },
      },
      expandable:{
        defaultExpandAllRows:true,
      }
    }
  }

  const submit = ()=>{

    form.validateFields().then((values) => {
      const {date,lang,platform,age,all} = values;
      const objectList = all;
      const productInfo = [];
      for (const key in objectList) {
        if (Object.hasOwnProperty.call(objectList, key)) {
          const item = objectList[key];
          productInfo.push(Object.assign({},{productId:key},item));
        }
      }
      const formData = {date,lang,platform,age,productInfo};
      alert(JSON.stringify(formData))
    });
  }

  return (
    <PageLayout>
       <Form layout="inline" form={form} name="form">
        <Row gutter={[15, 15]} style={{width:'100%'}}>
          <Col xs={24} sm={12} md={12} lg={8} xl={8}>
            <Form.Item label="日期" name='date'>
              <TimeRangeSelection />
            </Form.Item>
          </Col>
          <Col xs={24} sm={12} md={12} lg={8} xl={8}>
            <Form.Item label="语言" name='lang'>
               <Select data={langeList} valName='label' valKey='value' />
            </Form.Item>
          </Col>
          <Col xs={24} sm={12} md={12} lg={8} xl={8}>
            <Form.Item label="介绍" name='platform'>
              <Inputs/>
            </Form.Item>
          </Col>
          <Col>
            <Form.Item label="年龄" name='age'>
              <InputNumber/>
            </Form.Item>
          </Col>
          <Col xs={24} sm={12} md={12} lg={8} xl={8}>
            <Form.Item>
              <Button type="primary" onClick={submit}>提交</Button>
            </Form.Item>
          </Col>
        </Row>
        <Table {...datas.tableProps} loading={false} style={{width:'100%'}}/>
       </Form>
    </PageLayout>
  )
})

export default TableForm

// vue+typescript/src/views/form/table-form.vue
<template>
  <div class="com-page p20">
    <a-form ref="formRef" class="form" :model="form" label-align="left">
      <a-row :gutter="[15, 15]" type="flex" class="flex-wrap pb10">
        <a-col :xs="24" :sm="12" :md="12" :lg="8" :xl="8">
          <a-form-item label="日期" name="date">
            <TimeRangeSelection v-model:value="form.date" style="width: 100%"></TimeRangeSelection>
          </a-form-item>
        </a-col>
        <a-col :xs="24" :sm="12" :md="12" :lg="8" :xl="8">
          <a-form-item label="语言" name="lang">
            <a-select v-model:value="form.lang" show-search option-filter-prop="children" filter-option>
              <a-select-option v-for="item in langeListOptions" :key="item.value" :value="item.value">
                {{ item.label }}
              </a-select-option>
            </a-select>
          </a-form-item>
        </a-col>
        <a-col :xs="24" :sm="12" :md="12" :lg="8" :xl="8">
          <a-form-item label="介绍" name="platform">
            <a-input v-model:value="form.platform" placeholder="请填写"></a-input>
          </a-form-item>
        </a-col>
        <a-col style="flex: 0 0 160px; width: 160px">
          <a-form-item label="年龄" name="age">
            <a-input-number v-model:value="form.age"></a-input-number>
          </a-form-item>
        </a-col>
        <a-col :xs="24" :sm="12" :md="12" :lg="8" :xl="8">
          <a-form-item>
            <a-button type="primary" @click="onSubmit">提交</a-button>
          </a-form-item>
        </a-col>
      </a-row>
      <a-table :columns="columns" :data-source="form.dataSource" row-key="productId">
        <template #index="{ index }">
          <span>
            {{ index + 1 }}
          </span>
        </template>
        <template #productNumber="{ index }">
          <a-form-item
            label="数量"
            :name="['dataSource', index, 'productNumber']"
            :rules="[{ required: true, message: '请填写' }]"
          >
            <a-input-number v-model:value="form.dataSource[index].productNumber" :min="0"></a-input-number>
          </a-form-item>
        </template>
        <template #firstJourneyExpenses="{ index }">
          <a-form-item
            label="购买量"
            :name="['dataSource', index, 'firstJourneyExpenses']"
            :rules="[{ required: true, message: '请填写' }]"
          >
            <a-input-number v-model:value="form.dataSource[index].firstJourneyExpenses" :min="0"></a-input-number>
          </a-form-item>
        </template>
        <template #pictureurls="{ text }">
          <ComImage v-if="text" class-name="avatar" :src="text" fit="cover" @click="onImageClick(text)">
            <template #error><UserOutlined /></template>
          </ComImage>
        </template>
      </a-table>
    </a-form>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent, reactive, ref, unref } from 'vue'
import { UserOutlined } from '@ant-design/icons-vue'
import TimeRangeSelection from '@/components/time-range-selection/index.vue'
import { enumLangList } from '@/utils/enum'
import { imagePreview } from '@/components/image/image-preview'

const columnsData = [
  {
    key: 'index',
    dataIndex: 'index',
    title: '序号',
    align: 'center',
    slots: { customRender: 'index' },
    width: 200
  },
  {
    key: 'pictureurls',
    dataIndex: 'pictureurls',
    title: '图片',
    align: 'center',
    slots: { customRender: 'pictureurls' }
  },
  {
    key: 'productNumber',
    dataIndex: 'productNumber',
    title: '数量',
    align: 'center',
    slots: { customRender: 'productNumber' }
  },
  {
    key: 'firstJourneyExpenses',
    dataIndex: 'firstJourneyExpenses',
    title: '购买量',
    align: 'center',
    slots: { customRender: 'firstJourneyExpenses' }
  },
  {
    key: 'remarks',
    dataIndex: 'remarks',
    title: '备注',
    align: 'center'
  }
]

export default defineComponent({
  components: {
    UserOutlined,
    TimeRangeSelection
  },
  setup() {
    const formRef = ref()
    const form = reactive({
      date: [],
      lang: null,
      platform: '',
      age: '',
      dataSource: [
        {
          productId: 'odde43-de',
          pictureurls: 'https://antd-simple-pro.oss-cn-beijing.aliyuncs.com/image/1616494356149.png',
          productNumber: 0,
          firstJourneyExpenses: 0,
          remarks: '今天天气真好'
        },
        {
          productId: 'odde41-de',
          pictureurls: 'https://antd-simple-pro.oss-cn-beijing.aliyuncs.com/image/1616494473689.jpg',
          productNumber: 0,
          firstJourneyExpenses: 0,
          remarks: '你真的好漂亮呀'
        }
      ]
    })

    const columns = reactive(columnsData)

    const langeListOptions = reactive(enumLangList)

    const urlList = computed(() => {
      return form.dataSource.map(v => v.pictureurls)
    })

    function onSubmit() {
      formRef.value
        ?.validateFields()
        .then(() => {
          alert(JSON.stringify(form, null, 2))
        })
        .catch(console.log)
    }

    function onImageClick(url: string) {
      const urls = unref(urlList)
      imagePreview({
        urlList: urls,
        initialIndex: urls.findIndex(v => v === url)
      })
    }

    return {
      formRef,
      form,
      columns,
      langeListOptions,
      onSubmit,
      onImageClick
    }
  }
})
</script>

<style lang="less" scoped>
.form {
  ::v-deep(.ant-form-item) {
    display: flex;
    margin-bottom: 0;
  }

  ::v-deep(.ant-form-item-control-wrapper) {
    flex: 1;
  }
}

.avatar {
  width: 50px;
  height: 50px;
  border-radius: 50%;
  cursor: pointer;
}
</style>
