// vue+typescript/src/views/editor/codemirror.vue
<template>
  <div class="com-page p20">
    <Codemirror
      v-model:value="content"
      :options="{
        mode: 'javascript',
        theme: 'material',
        lineNumbers: true
      }"
      :autoScroll="false"
    ></Codemirror>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'
import Codemirror from '@/components/codemirror'
import 'codemirror/lib/codemirror.css'
import 'codemirror/theme/material.css'
require('codemirror/mode/xml/xml')
require('codemirror/mode/javascript/javascript')

const code = `
  // pages/home
  import { defineComponent, ref, onMounted } from 'vue'
  import { userList } from '@/api/login'
  export type UserListType={
    name: string
    aga: number
    sex: string
  }
  const App = defineComponent({
    setup() {
      const result = ref<UserListType[]>([])
      onMounted(() => {
        ;(async () => {
          const res = await userList({ username: 'li' })
          result.value = res.data
        })()
      })
      return () => {
        return (
          <>
            {
              !!result.value.length
              && (
                result.value.map((item, index) => (
                  <p key={index}>{item.name}</p>
                ))
              )
            }
          </>
        )
      }
    }
  })
  `

export default defineComponent({
  components: {
    Codemirror
  },
  setup() {
    const content = ref(code)
    return {
      content
    }
  }
})
</script>

<style lang="less" scoped>
.com-page {
  ::v-deep .CodeMirror {
    height: 600px;
  }
}
</style>

// react+typescript/src/pages/editor/codemirror.tsx
import React, { memo } from 'react';
import PageLayout from '@/layouts/pageLayout';
import { UnControlled as CodeMirror } from 'react-codemirror2';
import 'codemirror/lib/codemirror.css';
import 'codemirror/theme/material.css';
require('codemirror/mode/xml/xml');
require('codemirror/mode/javascript/javascript');

const Codemirror = memo(function Codemirror(props) {
  const jsCode = `
  // pages/home
  import React, {useEffect,useState} from 'react'
  import { userList } from '@/api/login'
  export type userListType={
      name:string;
      aga:number;
      sex:string
  };
  const App:React.FC=()=>{
    const [result, setResult] = useState<userListType[]>([]);
    useEffect(() => {
      const api=async ()=>{
          let res=await userList({username:'li'});
          setResult(res.data);
      }
      api();
    }, [])
      return (
      <>
          {result.length ?
              result.map((item,index)=>(
                   <p key={index}>{item.name}</p>
              ))
           : null}
      </>)
  }
  `;

  return (
    <PageLayout>
      <CodeMirror
        value={jsCode}
        options={{
          mode: 'javascript',
          theme: 'material',
          lineNumbers: true,
        }}
        autoScroll={false}
        className="CodeMirrorStyle"
        onChange={(editor, data, value) => {}}
      />
    </PageLayout>
  );
});

export default Codemirror;
