// vue+typescript/src/views/editor/json-editor.vue
<template>
  <div class="com-page p20">
    <div ref="container"></div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, onMounted, onBeforeUnmount } from 'vue'
import JSONEditor from 'jsoneditor'
import 'jsoneditor/dist/jsoneditor.css'

const json = {
  array: [1, 2, 3],
  boolean: true,
  null: null,
  number: 123,
  object: { a: 'b', c: 'd' },
  string: 'Hello World'
}

export default defineComponent({
  setup() {
    const editorInstance = ref<JSONEditor>()
    const container = ref<HTMLDivElement>()

    onMounted(() => {
      if (container.value) {
        editorInstance.value = new JSONEditor(container.value, {
          mode: 'tree',
          onChangeJSON: val => {
            console.log('val', val)
          }
        })
        editorInstance.value.set(json)
      }
    })

    onBeforeUnmount(() => {
      if (editorInstance.value) {
        editorInstance.value.destroy()
      }
    })

    return {
      container
    }
  }
})
</script>

<style lang="less" scoped>
.container {
  width: 100%;
  height: 100%;
}
</style>

// react+typescript/src/pages/editor/jsonEditor.tsx
import React, { memo,useEffect,useRef } from 'react'
import PageLayout from '@/layouts/pageLayout'
import JSONEditor,{ JSONEditorOptions } from 'jsoneditor';
import 'jsoneditor/dist/jsoneditor.css';

const JsonEditor = memo(function JsonEditor(props) {

  const json = {
    'array': [1, 2, 3],
    'boolean': true,
    'null': null,
    'number': 123,
    'object': {'a': 'b', 'c': 'd'},
    'string': 'Hello World'
  }

  const jsoneditor = useRef<JSONEditor>(null);

  const container = useRef<HTMLDivElement>(null);

  const onChangeJSON = (val:any) =>{
    console.log(`val`, val)
  }

  useEffect(() => {
    const options:JSONEditorOptions = {
      mode: 'tree',
      onChangeJSON
    };
    (jsoneditor.current as JSONEditor) = new JSONEditor(container.current!, options);
    jsoneditor.current!.set(json);
    return () => {
      jsoneditor && jsoneditor.current!.destroy();
    }
  }, []);

  return (
    <PageLayout>
      <div style={{height:'100%',width:'100%'}} ref={container} />
    </PageLayout>
  )
})

export default JsonEditor;
