// react/src/pages/user/index.js
import React, { memo, useEffect, useCallback, useState } from 'react'
import { useSetState } from '@/hooks'
import NoData from '@/components/noData'
import EditComponent from '@/container/userModule/userEdit'
import UserSearch from '@/container/userModule/userSearch'
import { LayoutTableComponent } from '@/components/layout/layoutTable'
import { SAGA_GET_USER_LIST } from '@/redux/constants/sagaType'
import { useSelector, useDispatch } from 'react-redux';
import { requestCode } from '@/utils/varbile'
import { Input, Image, Tooltip } from 'antd';
import { xlsxFileDown } from '@/api/login'
import { ArrowDownOutlined } from '@ant-design/icons';
import { createSelector } from 'reselect'
import Tools from '@/utils'
import '@/assets/scss/common.scss'

const User = memo(function User() {
  const columns = [
    {
      key: 'index',
      align: 'center',
      title: '序号',
      render: (text, record, index) => `${index + 1}`,
    },
    {
      align: 'center',
      title: 'id',
      dataIndex: 'id',
      key: 'id',
    },
    {
      align: 'center',
      title: 'email',
      dataIndex: 'email',
      key: 'email',
    },
    {
      align: 'center',
      title: '名称',
      dataIndex: 'username',
      key: 'username',
      render: (text) => <NoData data={text} />
    },
    {
      align: 'center',
      title: '介绍',
      dataIndex: 'introduct',
      key: 'introduct',
      render: (text) => <NoData data={text} />
    },
    {
      align: 'center',
      title: '头像',
      dataIndex: 'iconUrl',
      key: 'iconUrl',
      render: (text) => (
        <>
          {text.length ? <Image src={text} alt="头像" style={{ cursor: 'pointer' }} width={50} height={50} /> : <NoData data={text} />}
        </>
      )
    },
    {
      align: 'center',
      title: '操作',
      render: (text, record) => (
        <>
          <a onClick={() => handle(record)}>编辑</a>
        </>
      ),
    }
  ];

  const tools = new Tools();

  const [editData, setEditData] = useSetState({ visible: false, detailData: {} });

  const { Search } = Input;

  const [username, setUsername] = useState(undefined);

  const selectNumOfDoneTodos = createSelector( // 只计算，给的数据，其他的数据不会重新计算
    [(state) => state.user, (state) => state.other],
    (user, other) => [user.getUserList, other.loading]
  );

  const dispatch = useDispatch(); // 这里取代connect里面的dispatch

  const [getUserList, loading] = useSelector(selectNumOfDoneTodos); // 获取redux里面的数据，这里取代了connect函数

  const initFetch = useCallback((username) => dispatch({ type: SAGA_GET_USER_LIST, payload: { username } }), [dispatch]);

  useEffect(() => {
    initFetch(username)
  }, [initFetch, username])

  const downFile = async () => {
    let res = await xlsxFileDown();
    if (res.code === requestCode.successCode) {
      let delBuffer = Buffer.from(res.data, "binary");
      const blob = new Blob([delBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
      let url = window.URL.createObjectURL(blob);
      tools.createALabel(url);
    }
  }

  const datas = {
    btnGrounp: [{
      component: <Search
        enterButton
        placeholder="请输入用户名"
        onSearch={(value) => setUsername(value ? value : undefined)}
        style={{ width: 200 }}
        allowClear
      />
    }],
    iconGrounp: [
      {
        component: (<Tooltip title='下载' placement="bottom">
          <ArrowDownOutlined className='svg-fontSize' onClick={downFile} />
        </Tooltip>)
      }
    ],
    tableProps: { columns, dataSource: getUserList },
    receive: () => initFetch(username),
    loading
  }

  const handle = (detailData) => {
    setEditData({
      visible: true, detailData: Object.assign({}, detailData, {
        iconUrl: detailData.iconUrl.length ? detailData.iconUrl.split(',').map((item) => ({ uid: Math.random() * 100, url: item, response: { code: requestCode.successCode, data: { url: item } } })) : []
      })
    });
  }

  return (
    <>
      <LayoutTableComponent {...datas}>
        <UserSearch setUsername={setUsername} />
      </LayoutTableComponent>
      <EditComponent {...editData} onCancel={() => setEditData({ visible: false })} sucessCallback={() => initFetch(username)} />
    </>
  )
})

export default User;

// vue+typescript/src/views/user/index.vue
<template>
  <div class="com-page">
    <LayoutTable
      tableTitle="查询表格"
      :loading="loading"
      :tableProps="{
        columns,
        dataSource: userList,
        rowKey: v => v.id
      }"
      :pagination="{
        hideOnSinglePage: true
      }"
      :onRefresh="query"
    >
      <template #search>
        <a-form ref="form" layout="inline" :model="{}">
          <a-form-item label="名称">
            <a-input v-model:value="username" placeholder="请输入" allowClear></a-input>
          </a-form-item>
          <a-form-item>
            <a-space>
              <a-button type="primary" @click="query">查询</a-button>
              <a-button @click="onReset">重置</a-button>
            </a-space>
          </a-form-item>
        </a-form>
      </template>
      <template #buttons>
        <a-input-search
          v-model:value="username"
          placeholder="请输入用户名"
          enter-button
          allowClear
          @search="onSearch"
        />
      </template>
      <template #extraIcons>
        <a-tooltip title="下载" placement="bottom">
          <ArrowDownOutlined @click="onDownload" />
        </a-tooltip>
      </template>
      <template #index="{ index }">
        <span>
          {{ index + 1 }}
        </span>
      </template>
      <template #avatar="{ text }">
        <ComImage className="avatar" :src="text" @click="onImageClick(text)" fit="cover">
          <template v-slot:error><UserOutlined /></template>
        </ComImage>
      </template>
      <template #action="{ record }">
        <span>
          <a @click="onUpdate(record)">编辑</a>
        </span>
      </template>
    </LayoutTable>
    <UpdateUserModal
      v-model:visible="visible"
      :currentRow="currentRow"
      @update-success="onUpdateSuccess"
    ></UpdateUserModal>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, reactive, toRefs, computed, unref } from 'vue'
import userStore from '@/store/modules/user'
import LayoutTable from '@/components/layout-table'
import { ArrowDownOutlined, UserOutlined } from '@ant-design/icons-vue'
import { getUsers, getUsersBuffer } from './service'
import { useAsync } from '@/hooks'
import { downloadExcel } from '@/utils'
import UpdateUserModal from './update-user-modal.vue'
import imagePreview from '@/components/image/image-preview'
const columns = [
  {
    dataIndex: 'index',
    key: 'index',
    align: 'center',
    title: '序号',
    slots: { customRender: 'index' }
  },
  {
    dataIndex: 'id',
    key: 'id',
    align: 'center',
    title: 'id'
  },
  {
    dataIndex: 'email',
    key: 'email',
    align: 'center',
    title: 'email'
  },
  {
    dataIndex: 'username',
    key: 'username',
    align: 'center',
    title: '名称'
  },
  {
    dataIndex: 'introduct',
    key: 'introduct',
    align: 'center',
    title: '介绍'
  },
  {
    dataIndex: 'iconUrl',
    key: 'iconUrl',
    align: 'center',
    title: '头像',
    slots: { customRender: 'avatar' }
  },
  {
    key: 'action',
    align: 'center',
    title: '操作',
    slots: { customRender: 'action' }
  }
]

export default defineComponent({
  name: 'User',
  components: {
    LayoutTable,
    ArrowDownOutlined,
    UserOutlined,
    UpdateUserModal
  },
  setup() {
    const username = ref('')
    const state = reactive({
      columns,
      visible: false,
      currentRow: {}
    })

    const { data: userList, loading, run: query } = useAsync(
      () => {
        return getUsers({
          username: username.value
        })
      },
      {
        initialData: []
      }
    )

    const urlList = computed(() => {
      return userList.value.map(v => v.iconUrl)
    })

    function onUpdate(row: Record<string, unknown>) {
      state.currentRow = row
      state.visible = true
    }

    function onSearch() {
      setTimeout(() => {
        query()
      }, 20)
    }

    function onReset() {
      username.value = ''
      query()
    }

    function onImageClick(url: string) {
      const urls = unref(urlList)
      imagePreview({
        urlList: urls,
        initialIndex: urls.findIndex(v => v === url)
      })
    }

    function onUpdateSuccess() {
      query()
      userStore.getUserInfo()
    }

    async function onDownload() {
      try {
        const data = await getUsersBuffer()
        downloadExcel(data, '用户信息.xlsx')
      } catch (err) {
        console.log(err)
      }
    }

    return {
      userList,
      loading,
      ...toRefs(state),
      username,
      urlList,
      onDownload,
      query,
      onUpdate,
      onSearch,
      onReset,
      onImageClick,
      onUpdateSuccess
    }
  }
})
</script>

<style lang="less" scoped>
.avatar {
  width: 50px;
  height: 50px;
  border-radius: 50%;
  cursor: pointer;
}
</style>
