// react/src/pages/excel/selectExportExcel.js
import React, { memo, useEffect, useCallback, useState } from 'react'
import { useSetState } from '@/hooks'
import NoData from '@/components/noData'
import { LayoutTableComponent } from '@/components/layoutTable'
import { SAGA_GET_USER_LIST } from '@/redux/constants/sagaType'
import { connect } from 'react-redux';
import { Image,Radio,Button } from 'antd';
import { export_json_to_excel } from '@/utils/downExcel'
import { requestCode } from '@/utils/varbile'
import { toast } from '@/utils/function'
import { tHeader,filterVal,fileDataformat } from '@/pages/excel/exportExcel'

const User = memo(function User({ dispatch, getUserList, loading }) {

  const columns = [
    {
      key: 'index',
      align: 'center',
      title: '序号',
      render: (text, record, index) => `${index + 1}`,
    },
    {
      align: 'center',
      title: 'id',
      dataIndex: 'id',
      key: 'id',
    },
    {
      align: 'center',
      title: 'email',
      dataIndex: 'email',
      key: 'email',
    },
    {
      align: 'center',
      title: '名称',
      dataIndex: 'username',
      key: 'username',
      render: (text) => <NoData data={text} />
    },
    {
      align: 'center',
      title: '介绍',
      dataIndex: 'introduct',
      key: 'introduct',
      render: (text) => <NoData data={text} />
    },
    {
      align: 'center',
      title: '头像',
      dataIndex: 'iconUrl',
      key: 'iconUrl',
      render: (text) => (
        <>
          {text.length ? <Image src={text} alt="头像" style={{ cursor: 'pointer' }} width={50} height={50} /> : <NoData data={text} />}
        </>
      )
    }
  ];

  const [selectAllData, setSelectAllData] = useSetState({selectedRowKeys:[],selectedRows:[]});

  const typeList = ['xlsx','csv','txt'];

  const [ dowmLoading,setDowmLoading ] = useState(false);

  const [ type,setType ] = useState('xlsx');

  const initFetch = useCallback(() => dispatch({ type: SAGA_GET_USER_LIST}), [dispatch]);

  useEffect(() => {
    initFetch()
  }, [initFetch]);

  const typeChange = useCallback((e)=>setType(e.target.value));

  const rowSelection = {
    onChange: useCallback((selectedRowKeys, selectedRows) => {
      setSelectAllData({selectedRowKeys,selectedRows});
    }),
  };

  const datas = {
    btnGrounp: [{
      component: (<>
        <Radio.Group onChange={typeChange} defaultValue={type}>
          {typeList.map(item=>(
            <Radio value={item} key={item}>{item}</Radio>
          ))}
        </Radio.Group>
        <Button type="primary" onClick={()=>dowmZip()} loading={dowmLoading}>导出{type}</Button>
      </>)
    }],
    tableProps: {
      columns,
      dataSource: getUserList,
      rowSelection:{
        type:'checkbox',
        ...rowSelection,
        checkStrictly:true,
        selectedRowKeys:selectAllData.selectedRowKeys // 为了后面的清空操作
      },
    },
    receive: () => initFetch(),
    loading
  }

  const dowmZip = async ()=>{
    const { selectedRows } = selectAllData;
    if(!selectedRows.length){
      toast(requestCode.failedCode,'请先选择要导出的数据');
      return;
    }
    setDowmLoading(true);
    await export_json_to_excel({
      header: tHeader,
      data:fileDataformat(selectedRows,filterVal),
      filename: 'user',
      autoWidth: true,
      bookType: type
    });
    setDowmLoading(false);
    setSelectAllData({selectedRowKeys:[],selectedRows:[]});
  }

  return (
    <>
      <LayoutTableComponent {...datas} />
    </>
  )
})

export default connect(({ user, other }) => ({
  getUserList: user.getUserList,
  loading: other.loading
}))(User);

// vue+typescript/src/views/excel/select-export-excel/index.vue
<template>
  <div class="com-page">
    <LayoutTable
      tableTitle="查询表格"
      :loading="loading"
      :tableProps="{
        columns,
        dataSource: userList,
        rowKey: v => v.id,
        rowSelection: { selectedRowKeys, onChange: onSelectChange }
      }"
      :pagination="{
        hideOnSinglePage: true
      }"
      :onRefresh="query"
    >
      <template #buttons>
        <a-radio-group v-model:value="type">
          <a-radio v-for="(item, index) in typeList" :key="index" :value="item">
            {{ item }}
          </a-radio>
        </a-radio-group>
        <a-button type="primary" @click="onExport">导出{{ type }}</a-button>
      </template>
      <template #index="{ index }">
        <span>
          {{ index + 1 }}
        </span>
      </template>
      <template #avatar="{ text }">
        <ComImage className="avatar" :src="text" @click="onImageClick(text)" fit="cover">
          <template v-slot:error><UserOutlined /></template>
        </ComImage>
      </template>
    </LayoutTable>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, reactive, toRefs, computed, unref } from 'vue'
import LayoutTable from '@/components/layout-table'
import { UserOutlined } from '@ant-design/icons-vue'
import { getUsers } from '@/views/user/service'
import { useAsync } from '@/hooks'
import imagePreview from '@/components/image/image-preview'
import { exportJsonToExcel } from '@/utils/excel'
import { UserListItem } from '@/views/user/types'
import { isDefined } from '@/utils/type'
import { excelHeader, excelKeyList, normalizeExcelData } from '../types'
const columns = [
  {
    dataIndex: 'index',
    key: 'index',
    align: 'center',
    title: '序号',
    slots: { customRender: 'index' }
  },
  {
    dataIndex: 'id',
    key: 'id',
    align: 'center',
    title: 'id'
  },
  {
    dataIndex: 'email',
    key: 'email',
    align: 'center',
    title: 'email'
  },
  {
    dataIndex: 'username',
    key: 'username',
    align: 'center',
    title: '名称'
  },
  {
    dataIndex: 'introduct',
    key: 'introduct',
    align: 'center',
    title: '介绍'
  },
  {
    dataIndex: 'iconUrl',
    key: 'iconUrl',
    align: 'center',
    title: '头像',
    slots: { customRender: 'avatar' }
  }
]

function getSelectedRows(keys: number[], list: UserListItem[]) {
  return keys.map(key => list.find(item => item.id === key)).filter(isDefined)
}

type FileType = 'xlsx' | 'csv' | 'txt'

type StateType = {
  columns: typeof columns
  typeList: FileType[]
  selectedRowKeys: number[]
}

export default defineComponent({
  name: 'SelectExportExcel',
  components: {
    LayoutTable,
    UserOutlined
  },
  setup() {
    const username = ref('')
    const type = ref('xlsx')
    const state = reactive<StateType>({
      columns,
      typeList: ['xlsx', 'csv', 'txt'],
      selectedRowKeys: []
    })

    const { data: userList, loading, run: query } = useAsync(
      () => {
        return getUsers({
          username: username.value
        })
      },
      {
        initialData: []
      }
    )

    const urlList = computed(() => {
      return userList.value.map(v => v.iconUrl)
    })

    function onReset() {
      username.value = ''
      query()
    }

    function onImageClick(url: string) {
      const urls = unref(urlList)
      imagePreview({
        urlList: urls,
        initialIndex: urls.findIndex(v => v === url)
      })
    }

    function onExport() {
      exportJsonToExcel({
        data: normalizeExcelData(getSelectedRows(state.selectedRowKeys, unref(userList)), excelKeyList),
        header: excelHeader,
        filename: 'user',
        autoWidth: false,
        bookType: unref(type) as FileType
      })
    }

    function onSelectChange(selectedRowKeys: number[]) {
      state.selectedRowKeys = selectedRowKeys
    }

    return {
      userList,
      loading,
      ...toRefs(state),
      username,
      urlList,
      query,
      onReset,
      onImageClick,
      type,
      onExport,
      onSelectChange
    }
  }
})
</script>

<style lang="less" scoped>
.avatar {
  width: 50px;
  height: 50px;
  border-radius: 50%;
  cursor: pointer;
}
</style>
