// react/src/pages/qrCode/index.js
import React, { memo,useEffect,useState } from 'react'
import QRCode from 'qrcode.react';
import PageLayout from '@/layouts/pageLayout'
import { Form, InputNumber , Button, Row,Col,Switch } from 'antd';
import InputCompent from '@/components/input';
import { useSetState } from '@/hooks'
import { saveAs } from 'file-saver';
import Logo from '@/assets/image/Icon_512x512-15@1x@1x.png'
import ImgUpload from '@/components/upload/imgUpload'
import { requestCode } from '@/utils/varbile';

export const defalutVal = {
  linkUrl:'https://lgf196.top/react/home',
  size:200,
  logoUrl:Logo,
  logoW:70,
  logoH:70,
  excavate:false
};

const Index = memo(function Index() {

  const [form] = Form.useForm();

  const [base64Url,setBase64Url] = useState(Logo);

  const [config,setConfig] = useSetState(defalutVal);

  useEffect(() => {
    form.setFieldsValue({...defalutVal,logoUrl:[{
      uid: '-1',
      status: 'success',
      response: {
        code: requestCode.successCode,
        data: { url: Logo },
      },
      url:Logo,
    }]})
  }, [])

  const onFinish = (values) => {
    setConfig(Object.assign({},values,{logoUrl:base64Url}))
  };

  const dowm = ()=>{
    const canvasImg = document.getElementById('qrCode');
    canvasImg.setAttribute('crossorigin', 'Anonymous');
    canvasImg.toBlob(function(blob) {
      saveAs(blob, "ant-simple-pro.png");
    });
  }

  const handleChnage = (val)=>{
    if(val.length){
      if(val[0].thumbUrl){
        setBase64Url(val[0].thumbUrl ? val[0].thumbUrl : Logo);
        return ;
      }
    }else{
      setBase64Url(Logo);
    }
  }

  return (
    <PageLayout>
       <Row gutter={[10, 10]}>
        <Col xs={24} sm={24} md={12} lg={5} xl={5}>
            <QRCode
              id="qrCode"
              value={config.linkUrl}
              size={config.size} // 二维码的大小
              fgColor="#000000" // 二维码的颜色
              style={{ margin: 'auto' }}
              imageSettings={{ // 二维码中间的logo图片
                src: config.logoUrl,
                height: config.logoH,
                width: config.logoW,
                excavate:config.excavate
            }}
          />
          <Button type="primary" onClick={dowm} style={{marginTop:'10px'}}>下载二维码</Button>
        </Col>
        <Col xs={24} sm={24} md={12} lg={19} xl={19}>
          <Form form={form} labelAlign='left' onFinish={onFinish}>
            <Form.Item label="链接url" name="linkUrl" rules={[{ required: true, message: '请填写' }]}>
              <InputCompent size='middle' />
            </Form.Item>
            <Form.Item label="二维码大小" name="size" rules={[{ required: true, message: '请填写' }]}>
              <InputNumber min={50}/>
            </Form.Item>
            <Form.Item label={(<p>中间logo图url<span style={{color:'red'}}>必须是透明的底</span></p>)} name="logoUrl"  valuePropName="fileList" >
              <ImgUpload limit={1} onChange={handleChnage} />
            </Form.Item>
            <Form.Item label="logon宽" name="logoW" >
              <InputNumber min={10}/>
            </Form.Item>
            <Form.Item label="logon高" name="logoH">
              <InputNumber min={10}/>
            </Form.Item>
            <Form.Item label="logo是否镂空" name="excavate" valuePropName="checked">
              <Switch checkedChildren="是" unCheckedChildren="否" />
            </Form.Item>
            <Form.Item >
              <Button type="primary" htmlType="submit">
                生产二维码
              </Button>
            </Form.Item>
          </Form>
        </Col>
       </Row>
    </PageLayout>
  )
})

export default Index;

// vue/src/views/qrcode/index.vue
<template>
  <div class="com-page p20">
    <a-row :gutter="[10, 10]">
      <a-col :xs="24" :sm="24" :md="12" :lg="5" :xl="5">
        <VueQrcode
          ref="qrcodeRef"
          canvas-class="canvas-qrcode"
          :value="config.linkUrl"
          :size="config.size"
          :style="{ margin: 'auto' }"
          :image-settings="{
            src: config.logoUrl,
            width: config.logoW,
            height: config.logoH,
            excavate: config.excavate
          }"
        ></VueQrcode>
        <a-button type="primary" class="mt10" @click="onDown"> 下载二维码 </a-button>
      </a-col>
      <a-col :xs="24" :sm="24" :md="12" :lg="19" :xl="19">
        <a-form class="form" :model="form" :rules="rules" label-align="left" @finish="onFinish">
          <a-form-item label="链接url" name="linkUrl">
            <a-input v-model:value="form.linkUrl" placeholder="请填写" />
          </a-form-item>
          <a-form-item label="二维码大小" name="size">
            <a-input-number v-model:value="form.size" placeholder="请填写" :min="50" />
          </a-form-item>
          <a-form-item name="fileList">
            <template #label>
              <span>中间logo图url</span>
              <span class="text-color-danger">必须是透明的底</span>
            </template>
            <ComUploadImage v-model:value="form.fileList" :limit="1"></ComUploadImage>
          </a-form-item>
          <a-form-item label="logo宽" name="logoW">
            <a-input-number v-model:value="form.logoW" placeholder="请填写" :min="10" />
          </a-form-item>
          <a-form-item label="logo高" name="logoH">
            <a-input-number v-model:value="form.logoH" placeholder="请填写" :min="10" />
          </a-form-item>
          <a-form-item label="是否镂空" name="excavate">
            <a-switch v-model:checked="form.excavate"></a-switch>
          </a-form-item>
          <a-form-item class="form-item--submit">
            <a-button class="submit-btn" type="primary" html-type="submit"> 生成二维码 </a-button>
          </a-form-item>
        </a-form>
      </a-col>
    </a-row>
  </div>
</template>

<script>
import { defineComponent, ref } from 'vue'
import { saveAs } from 'file-saver'
import VueQrcode from '@/components/qrcode'
import Logo from '@/assets/images/Icon_512x512-15@1x@1x.png'
export const defalutVal = {
  linkUrl: 'https://lgf196.top/react/home',
  size: 200,
  logoUrl: Logo,
  logoW: 70,
  logoH: 70,
  excavate: false
}
export default defineComponent({
  components: {
    VueQrcode
  },
  setup() {
    const linkUrl = ref(defalutVal.linkUrl)
    const logoUrl = ref(Logo)
    const qrcodeRef = ref(null)
    const rules = ref({
      linkUrl: [{ required: true, message: '请填写' }],
      size: [{ required: true, message: '请填写' }]
    })
    const form = ref({
      linkUrl: defalutVal.linkUrl,
      size: defalutVal.size,
      fileList: [Logo],
      logoW: defalutVal.logoW,
      logoH: defalutVal.logoH,
      excavate: defalutVal.excavate
    })
    const config = ref({
      linkUrl: defalutVal.linkUrl,
      size: defalutVal.size,
      logoUrl: Logo,
      logoW: defalutVal.logoW,
      logoH: defalutVal.logoH,
      excavate: defalutVal.excavate
    })

    function onDown() {
      // const canvas = unref(qrcodeRef)
      const canvas = document.querySelector('.canvas-qrcode')
      console.log('canvas', canvas)
      canvas.setAttribute('crossorigin', 'Anonymous')
      canvas.toBlob(blob => {
        if (blob) {
          saveAs(blob, 'ant-simple-pro.png')
        }
      })
    }

    function onFinish(values) {
      const { fileList, ...otherValues } = values
      config.value = Object.assign({}, otherValues, {
        logoUrl: fileList[0]
      })
    }

    return {
      linkUrl,
      logoUrl,
      qrcodeRef,
      form,
      rules,
      config,
      onDown,
      onFinish
    }
  }
})
</script>

<style lang="less" scoped>
.form {
  ::v-deep(.ant-form-item) {
    display: flex;
  }

  ::v-deep(.ant-form-item-control-wrapper) {
    flex: 1;
  }
}
</style>
