// vue/src/views/globalization/index.vue
<template>
  <div class="com-page">
    <div>
      <a-radio-group
        v-model:value="language"
        button-style="solid"
        @change="onToggle"
      >
        <a-radio-button
          v-for="(item, index) in languages"
          :key="index"
          :value="item.value"
        >
          {{item.title}}
        </a-radio-button>
      </a-radio-group>
      <a href="https://github.com/intlify/vue-i18n-next" target="_blank">
        <a-button type="link">
          了解vue-i18n-next
        </a-button>
      </a>
    </div>
    <a-list item-layout="vertical" size="large" :data-source="listData">
      <template #renderItem="{ item }">
        <a-list-item key="item.title">
          <template #actions>
            <span v-for="{ type, text } in actions" :key="type">
              <component v-bind:is="type" style="margin-right: 8px" />
              {{ text }}
            </span>
          </template>
          <template #extra>
            <img
              width="272"
              alt="logo"
              src="https://gw.alipayobjects.com/zos/rmsportal/mqaQswcyDLcXyDKnZfES.png"
            />
          </template>
          <a-list-item-meta :description="$t('description')">
            <template #title>
              <a :href="item.href">Ant Simple Pro</a>
            </template>
            <template #avatar>
              <a-avatar :size="30" style="backgroundColor: #fff">
                <template #icon>
                  <ComSvgIcon name="logo" class="icon-logo"></ComSvgIcon>
                </template>
              </a-avatar>
            </template>
          </a-list-item-meta>
          {{ $t('content') }}
        </a-list-item>
      </template>
    </a-list>
  </div>
</template>

<script>
import { StarOutlined, LikeOutlined, MessageOutlined } from '@ant-design/icons-vue'
const listData = []
for (let i = 0; i < 3; i++) {
  listData.push({
    href: 'https://github.com/lgf196/ant-simple-pro',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png'
  })
}
export default {
  name: 'Globalization',
  components: {
    StarOutlined,
    LikeOutlined,
    MessageOutlined
  },
  data() {
    return {
      language: 'en',
      languages: [
        { title: '英文', value: 'en' },
        { title: '中文', value: 'zh' },
        { title: '日文', value: 'ja' }
      ],
      listData,
      actions: [
        { type: 'StarOutlined', text: '156' },
        { type: 'LikeOutlined', text: '156' },
        { type: 'MessageOutlined', text: '2' }
      ]
    }
  },
  methods: {
    onToggle() {
      this.$i18n.locale = this.language
    }
  }
}
</script>

<style lang="less" scoped>
  .icon-logo {
    font-size: 30px;
  }
  ::v-deep .ant-list-item {
    padding: 16px 24px;
  }
</style>

// frontEnd/src/pages/globalization/index.tsx
import React, { memo } from 'react'
import { useTranslation } from 'react-i18next';
import { MessageOutlined, LikeOutlined, StarOutlined } from '@ant-design/icons';
import { Radio, List, Space } from 'antd';
import SvgIcon from '@/components/svgIcon';
import { RadioChangeEvent } from 'antd/lib/radio';
import '@/il8n';
const Globalization = memo(function Globalization(props) {
    const { t, i18n } = useTranslation();
    const listData: any[] | undefined = [];
    for (let i = 0; i <3; i++) {
        listData.push({
            index:i,
            title: `Ant Simple Pro`,
            avatar:<SvgIcon iconClass='logon' fontSize='30px'/>,
            description:t('description'),
            content:t('content')
        });
    }
    const IconText = ({ icon, text }: any) => (
        <Space>
            {React.createElement(icon)}
            {text}
        </Space>
    );
    const change=(val:RadioChangeEvent)=>{
        const lang=val.target.value;
        i18n.changeLanguage(lang);
    }
    return (
        <div className='bgW padding-10px'>
            <div>
                <Radio.Group defaultValue="en" buttonStyle="solid" onChange={change}>
                    <Radio.Button value="en">英文</Radio.Button>
                    <Radio.Button value="zh">中文</Radio.Button>
                    <Radio.Button value="ja">日文</Radio.Button>
                </Radio.Group>
                <a href="https://react.i18next.com/" style={{padding:'0 10px'}} target='_blank'>了解过多react-i18next信息</a>
            </div>
            <List
                itemLayout="vertical"
                size="large"
                dataSource={listData}
                renderItem={item => (
                    <List.Item
                        key={item.index}
                        actions={[
                            <IconText icon={StarOutlined} text="156" key="list-vertical-star-o" />,
                            <IconText icon={LikeOutlined} text="156" key="list-vertical-like-o" />,
                            <IconText icon={MessageOutlined} text="2" key="list-vertical-message" />,
                        ]}
                        extra={
                            <img
                                width={272}
                                alt="logo"
                                src="https://gw.alipayobjects.com/zos/rmsportal/mqaQswcyDLcXyDKnZfES.png"
                            />
                        }
                    >
                        <List.Item.Meta
                            avatar={item.avatar}
                            title={<a href={item.href}>{item.title}</a>}
                            description={item.description}
                        />
                        {item.content}
                    </List.Item>
                )}
            />
        </div>
    )
})
export default Globalization
