// frontEnd/src/pages/package/chart/index.tsx
import React, { memo} from 'react'
import Columnar from './components/columnar'
import Bar from './components/bar'
import LineMap from './components/lineMap'
import Pie from './components/pie'
import { Row, Col } from 'antd';
const Chart = memo(function Chart() {
    return (
        <>
            <Row gutter={[10,10]}>
                <Col xs={24} sm={24} md={24} lg={24} xl={12} >
                    <Columnar/>
                </Col>
                <Col xs={24} sm={24} md={24} lg={24} xl={12} >
                     <Bar/>
                </Col> 
                <Col xs={24} sm={24} md={24} lg={24} xl={12} >
                    <LineMap/>
                </Col> 
                <Col xs={24} sm={24} md={24} lg={24} xl={12} >
                    <Pie/>
                </Col>
            </Row>
        </>
    )
})

export default Chart

// vue/src/views/component/chart/index.vue
<template>
  <div class="com-page">
    <a-row :gutter="[10, 10]">
      <a-col
        :xs="24"
        :sm="24"
        :md="24"
        :lg="24"
        :xl="12"
      >
        <Column></Column>
      </a-col>
      <a-col
        :xs="24"
        :sm="24"
        :md="24"
        :lg="24"
        :xl="12"
      >
        <Bar></Bar>
      </a-col>
      <a-col
        :xs="24"
        :sm="24"
        :md="24"
        :lg="24"
        :xl="12"
      >
        <Line></Line>
      </a-col>
      <a-col
        :xs="24"
        :sm="24"
        :md="24"
        :lg="24"
        :xl="12"
      >
        <Pie></Pie>
      </a-col>
    </a-row>
  </div>
</template>

<script>
import Column from './components/column'
import Bar from './components/bar'
import Line from './components/line'
import Pie from './components/pie'
export default {
  name: 'Chart',
  components: {
    Column,
    Bar,
    Line,
    Pie
  },
  data() {
    return {}
  }
}
</script>

<style lang="less" scoped>
.com-page {
  background-color: transparent;
}
::v-deep .ant-col > div {
  background-color: #fff;
}
</style>
