// vue/src/views/login/index.vue
<template>
  <div class="login">
    <a-row class="login-main" type="flex" align="middle" justify="space-around">
      <aside class="aside"></aside>
      <div class="form-container">
        <a-row class="logo" type="flex" align="middle" justify="center">
          <img class="image" src="@/assets/images/logo.png" />
          <h1 class="title">Ant Simple Pro</h1>
        </a-row>
        <a-form
          class="form"
          :model="form"
          :rules="rules"
          @finish="handleFinish"
        >
          <a-form-item has-feedback name="email">
            <a-input
              v-model:value="form.email"
              placeholder="请填写邮箱"
              size="large"
            >
              <template #prefix>
                <UserOutlined class="form-item-prefix" />
              </template>
            </a-input>
          </a-form-item>
          <a-form-item has-feedback name="password">
            <a-input
              type="password"
              v-model:value="form.password"
              placeholder="请填写密码"
              size="large"
            >
              <template #prefix>
                <LockOutlined class="form-item-prefix" />
              </template>
            </a-input>
          </a-form-item>
          <!-- <a-form-item name="remember">
            <a-checkbox v-model:checked="form.remember">
              记住密码
            </a-checkbox>
          </a-form-item> -->
          <a-form-item class="form-item--submit">
            <a-button
              class="submit-btn"
              type="primary"
              html-type="submit"
              size="large"
              :loading="loading"
            >
              登录
            </a-button>
          </a-form-item>
        </a-form>
      </div>
    </a-row>
    <FooterBar class="login-footer"></FooterBar>
  </div>
</template>

<script>
// import md5 from 'md5'
import { mapGetters } from 'vuex'
import { UserOutlined, LockOutlined } from '@ant-design/icons-vue'
import { login } from './service'
import {
  getRememberUser,
  setRememberUser,
  removeRememberUser,
  setToken
} from '@/utils/local'
import FooterBar from '@/components/footerbar'
export default {
  components: {
    FooterBar,
    UserOutlined,
    LockOutlined
  },
  data() {
    return {
      form: {
        email: '',
        password: '',
        remember: false
      },
      rules: {
        email: [
          { required: true, message: '请填写邮箱!', trigger: 'blur' },
          { type: 'email', message: '邮箱格式不正确!', trigger: 'blur' }
        ],
        password: [{ required: true, message: '请填写密码!', trigger: 'blur' }]
      }
    }
  },
  computed: {
    ...mapGetters(['loading'])
  },
  mounted() {
    const rememberUser = getRememberUser()
    if (rememberUser) {
      this.form = rememberUser
    }
  },
  methods: {
    async handleFinish(values) {
      if (values.remember) {
        setRememberUser(values)
      } else {
        removeRememberUser()
      }
      const params = {
        email: values.email,
        // password: md5(md5(values.password))
        password: values.password
      }
      try {
        const token = await login(params)
        setToken(token) // save local
        await this.$store.dispatch('user/GetUserData')
        this.$router.push('/')
        this.$message.destroy()
        this.$message.success('登录成功')
      } catch (err) {
        console.log(err)
      }
    }
  }
}
</script>

<style lang="less" scoped>
.login {
  height: 100vh;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  background: #fff;
}
.login-main {
  flex: auto;
  &:before,
  &:after {
    content: '';
  }
}
.aside {
  width: 46.5vw;
  height: 86vh;
  background: url('~@/assets/images/login.png') center no-repeat;
  background-size: contain;
}
.form-container {
  width: 360px;
  padding: 50px;
  border-radius: 2px;
  box-shadow: 0 0 40px 0 rgba(24, 144, 255, 0.1),
    0 55px 85px -60px rgba(24, 144, 255, 0.31);
  background-color: #fff;
  .logo {
    .image {
      width: 30px;
      height: 30px;
      margin-right: 8px;
    }
    .title {
      color: @color-theme;
      font-size: 16px;
    }
  }
  .form {
    padding-top: 30px;
    .submit-btn {
      width: 100%;
      border: 0;
    }
  }
  .form-item-prefix {
    color: rgba(0, 0, 0, 0.25);
  }
  .form-item--submit {
    margin-bottom: 0;
    padding-top: 26px;
  }
}
@media screen and (max-width: 1080px) {
  .aside {
    display: none;
  }
}
</style>

// react/src/pages/login/index.js
import React from 'react'
import { Form, Button, Input } from 'antd';
import { login } from '@/api/login'
import { useHistory } from "react-router-dom";
import { requestCode } from '@/utils/varbile'
import { useSelector } from 'react-redux';
import SvgIcon from '@/components/svgIcon'
import { UserOutlined, LockOutlined } from '@ant-design/icons';
import { Footer } from '@/layouts/basic/component'
import style from './login.module.scss'
import logon from '@/assets/image/pic.svg'

const Login = () => {
  const history = useHistory();

  const loading = useSelector(({ other }) => other.loading);

  const onFinish = async (values) => {
    const { email, password } = values
    let res = await login({ email, password });
    if (res.code === requestCode.successCode) {
      localStorage.setItem('token', res.data);
      history.push("/home");
    }
  };

  return (
    <div className={style.login}>
      <div className={style.content}>
        <div className={style.bg}>
          <img src={logon} alt="logon" />
        </div>
        <div className={style.fill}>
          <div className={style.logon}>
            <SvgIcon iconClass='logon' fontSize='30px' className={style.img} />
            <h2>Ant Simple Pro</h2>
          </div>
          <div className={style.from}>
            <Form name="basic" initialValues={{ remember: true }} layout='vertical' onFinish={onFinish}>
              <Form.Item name="email" rules={[{ required: true, message: '请输入邮箱' }]}>
                <Input
                  prefix={<UserOutlined style={{ color: 'rgba(0, 0, 0, 0.25)' }} />}
                  placeholder="请填写邮箱"
                  size='large'
                  allowClear
                />
              </Form.Item>
              <Form.Item name="password" rules={[{ required: true, message: '请输入密码' }]}>
                <Input
                  prefix={<LockOutlined style={{ color: 'rgba(0, 0, 0, 0.25)' }} />}
                  type="password"
                  placeholder="请填写密码"
                  size='large'
                  allowClear
                />
              </Form.Item>
              <Form.Item className={style.space}>
                <Button type="primary" htmlType="submit"
                  loading={loading}
                  className={style.submit}
                  size='large'
                >
                  登录
                </Button>
              </Form.Item>
            </Form>
          </div>
        </div>
      </div>
      <Footer name='Ant Simple Pro' ahthor='Lgf&qyh' />
    </div>
  )
}

export default Login;
