// frontEnd/src/pages/user/index.tsx
import React, { memo ,useEffect,useCallback,useState} from 'react'
import {useSetState} from '@/hooks'
import NoData from '@/components/noData'
import EditComponent from '@/container/user-module/userEdit'
import UserSearch from '@/container/user-module/userSearch'
import {LayoutTableComponent} from '@/components/layout/layoutTable'
import {SAGA_GET_USER_LIST} from '@/redux/constants/sagaType'
import { ColumnProps} from 'antd/lib/table';
import { connect } from 'react-redux';
import { Dispatch } from 'redux';
import {getUserType} from '@/interfaces'
import { LayoutTablePropsType } from '@/components/layout/layoutTable/main'
import { requestCode } from '@/utils/varbile'
import { Input,Image, Tooltip } from 'antd';
import {sagaGetUserDataType} from '@/redux/saga/user'
import {userListType,xlsxFileDown} from '@/api/login'
import { ArrowDownOutlined } from '@ant-design/icons';
import tools from '@/utils'
import '@/assets/scss/common.scss'
export interface UserProps extends loading{
    dispatch:Dispatch<sagaGetUserDataType>,
    getUserList:getUserType[]
}
const User:React.FC<UserProps> = memo(function User({dispatch,getUserList,loading}) {
    const columns:ColumnProps<getUserType>[]=[
        {
            key: 'index',
            align:'center',
            title: '序号',
            render:(text,record,index)=>`${index+1}`,
        },
        {
            align:'center',
            title: 'id',
            dataIndex: 'id',
            key: 'id',
        },
        {
            align:'center',
            title: 'email',
            dataIndex: 'email',
            key: 'email',
        },
        {
            align:'center',
            title: '名称',
            dataIndex: 'username',
            key: 'username',
            render:(text)=><NoData data={text}/>
        },
        {
            align:'center',
            title: '介绍',
            dataIndex: 'introduct',
            key: 'introduct',
            render:(text)=><NoData data={text}/>
        },
        {
            align:'center',
            title: '头像',
            dataIndex: 'iconUrl',
            key: 'iconUrl',
            render:(text)=>(
                <>
                  {text.length?<Image src={text} alt="头像" style={{cursor:'pointer'}} width={50} height={50}/>:<NoData data={text}/>}
                </>
            )
        },
        {
            align:'center',
            title: '操作',
            render: (text, record) => (
                <>
                    <a  onClick={()=>handle(record)}>编辑</a>
                </>
            ),
        }
    ];
    const [editData, setEditData] =useSetState({visible:false,detailData:{}});
    const { Search } = Input;
    const [username,setUsername]=useState<userListType['username']>(undefined);
    const initFetch=useCallback((username)=> dispatch({type:SAGA_GET_USER_LIST,payload:{username}}),[dispatch]);
    useEffect(() => {
        initFetch(username)
    }, [initFetch,username])
    const downFile=async ()=>{
        let res=await xlsxFileDown();
        if(res.code===requestCode.successCode){
           let delBuffer = Buffer.from(res.data, "binary");
           const blob = new Blob([delBuffer], { type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
           let url = window.URL.createObjectURL(blob);
           tools.createALabel(url);
       }
   }
    const datas:LayoutTablePropsType={
        btnGrounp:[{
            component:<Search
            enterButton 
            placeholder="请输入用户名"
            onSearch={(value) =>setUsername(value?value:undefined)}
            style={{ width: 200 }}
            allowClear
          />
        }],
        iconGrounp:[
            {
                // component: (<Tooltip title='下载' placement="bottom">
                //     <ArrowDownOutlined  className='svg-fontSize' onClick={downFile}/>
                // </Tooltip>)
            }
        ],
        tableProps:{columns,dataSource:getUserList},
        receive:()=> initFetch(username),
        loading
    }
    const handle=(detailData:editDataProps<getUserType>['detailData'])=>{
        setEditData({visible:true,detailData:Object.assign({},detailData,{
            iconUrl:detailData.iconUrl.length?detailData.iconUrl.split(',').map((item) => ({uid:Math.random()*100,url:item,response:{code:requestCode.successCode,data:{url:item}}})):[]
        })});
    }
    return (
        <>
             <LayoutTableComponent {...datas}>
                <UserSearch setUsername={setUsername}/>
             </LayoutTableComponent>
             <EditComponent {...editData} onCancel={()=>setEditData({visible:false})} sucessCallback={()=>initFetch(username)}/>
        </>
    )
})

export default connect(({user,other}:reduceStoreType)=>({
    getUserList:user.getUserList,
    loading:other.loading
}))(User);

// vue/src/views/user/index.vue
<template>
  <div class="com-page">
    <LayoutTable
      tableTitle="查询表格"
      :loading="loading"
      :tableProps="{
        columns,
        dataSource: userList,
        rowKey: v => v.id
      }"
      :pagination="false"
      :onRefresh="run"
    >
      <template #search>
        <a-form
          ref="form"
          layout="inline"
          :model="{}"
        >
          <a-form-item label="名称">
            <a-input v-model:value="username" placeholder="请输入" allowClear></a-input>
          </a-form-item>
          <a-form-item>
            <a-space>
              <a-button type="primary" @click="handleSubmit">
                查询
              </a-button>
              <a-button @click="onReset">
                重置
              </a-button>
            </a-space>
          </a-form-item>
        </a-form>
      </template>
      <template #buttons>
        <a-input-search
          v-model:value="username"
          placeholder="请输入用户名"
          enter-button
          allowClear
          @search="onSearch"
        />
      </template>
      <template #extraIcons>
        <a-tooltip title="下载" placement="bottom">
          <ArrowDownOutlined @click="onDownload" />
        </a-tooltip>
      </template>
      <template #index="{ index }">
        <span>
          {{index + 1}}
        </span>
      </template>
      <template #avatar="{ text }">
        <ComImage className="avatar" :src="text" @click="onImageClick(text)" fit="cover">
          <template v-slot:error><UserOutlined /></template>
        </ComImage>
      </template>
      <template #action="{ record }">
        <span>
          <a @click="onUpdate(record)">编辑</a>
        </span>
      </template>
    </LayoutTable>
    <UpdateUserModal
      v-model:visible="visible"
      :currentRow="currentRow"
      @updateSuccess="onUpdateSuccess"
    >
    </UpdateUserModal>
  </div>
</template>

<script>
import { ref } from 'vue'
import LayoutTable from '@/components/layout-table'
import {
  ArrowDownOutlined,
  UserOutlined
} from '@ant-design/icons-vue'
import { getUsers, getUsersBuffer } from './service'
import useRequest from '@/hooks/useRequest'
import { downloadExcel } from '@/utils'
import UpdateUserModal from './update-user-modal'
const columns = [
  {
    dataIndex: 'index',
    key: 'index',
    align: 'center',
    title: '序号',
    slots: { customRender: 'index' }
  },
  {
    dataIndex: 'id',
    key: 'id',
    align: 'center',
    title: 'id'
  },
  {
    dataIndex: 'email',
    key: 'email',
    align: 'center',
    title: 'email'
  },
  {
    dataIndex: 'username',
    key: 'username',
    align: 'center',
    title: '名称'
  },
  {
    dataIndex: 'introduct',
    key: 'introduct',
    align: 'center',
    title: '介绍'
  },
  {
    dataIndex: 'iconUrl',
    key: 'iconUrl',
    align: 'center',
    title: '头像',
    slots: { customRender: 'avatar' }
  },
  {
    key: 'action',
    align: 'center',
    title: '操作',
    slots: { customRender: 'action' }
  }
]

export default {
  name: 'User',
  components: {
    LayoutTable,
    ArrowDownOutlined,
    UserOutlined,
    UpdateUserModal
  },
  data() {
    return {
      columns,
      visible: false,
      currentRow: {}
    }
  },
  computed: {
    urlList() {
      return this.userList.map(v => v.iconUrl)
    }
  },
  setup() {
    const username = ref('')
    const { data: userList = [], run, loading } = useRequest(() => getUsers({
      username: username.value
    }))
    console.log('userList', userList)
    return {
      userList,
      username,
      run,
      loading
    }
  },
  methods: {
    handleSubmit() {
      this.run()
    },
    onUpdate(row) {
      this.currentRow = row
      this.visible = true
    },
    onSearch() {
      setTimeout(() => {
        this.run()
      }, 20)
    },
    onReset() {
      this.username = ''
      this.run()
    },
    onImageClick(url) {
      this.$imagePreview({
        urlList: this.urlList,
        initialIndex: this.urlList.findIndex(v => v === url)
      })
    },
    async onDownload() {
      try {
        const data = await getUsersBuffer()
        downloadExcel(data, '用户信息.xlsx')
      } catch (err) {
        console.log(err)
      }
    },
    onUpdateSuccess() {
      this.run()
      this.$store.dispatch('user/GetUserInfo')
    }
  }
}
</script>

<style lang="less" scoped>
  .avatar {
    width: 50px;
    height: 50px;
    border-radius: 50%;
    cursor: pointer;
  }
</style>
