// frontEnd/src/pages/stystem/menu.tsx
import React, { memo,useEffect } from 'react'
import {SAGA_GETMENULIST} from '@/redux/constants/sagaType'
import { ColumnProps } from 'antd/lib/table';
import useSetState from '@/hooks/useSetState'
import { connect } from 'react-redux';
import {Tooltip } from 'antd'
import { Dispatch } from 'redux';
import Table from '@/components/table'
import NoData from '@/components/noData'
import {menuAccessType,LayoutTableProps} from '@/interfaces'
import Buttons from '@/components/button'
import Pagination from '@/components/pagination'
import {SyncOutlined} from '@ant-design/icons';
import '@/assets/scss/common.scss'
import Line from '@/components/line'
import LayoutTableComponent from '@/components/layout/layoutTable'
import MenuOption from '@/container/stystem/option'
export interface menuListType{
    dispatch:Dispatch,
    getMenuList:menuAccessType[]
}
const Menu:React.FC<menuListType> = memo(function Menu({dispatch,getMenuList}) {
    const columns:ColumnProps<{id:number}>[]=[
        {
            key: 'index',
            align:'center',
            title: '序号',
            render:(text,record,index)=>`${index+1}`,
        },
        {
            align:'center',
            title: 'id',
            dataIndex: 'id',
            key: 'id',
        },
        {
            align:'center',
            title: 'pid',
            dataIndex: 'pid',
            key: 'pid',
        },
        {
            align:'center',
            title: '名称',
            dataIndex: 'title',
            key: 'title',
            render:(text)=><NoData data={text}/>
        },
        {
            align:'center',
            title: 'url',
            dataIndex: 'url',
            key: 'url',
        },
        {
            align:'center',
            title: 'icon',
            dataIndex: 'icon',
            key: 'icon',
            render:(text)=><NoData data={text}/>
        },
        {
            align:'center',
            title: '创建时间',
            dataIndex: 'createTime',
            key: 'createTime',
        },
        {
            align:'center',
            title: '操作',
            render: (text, record) => (
                <>
                    <a>编辑</a>
                    <Line/>
                    <a style={{color:'#ff4d4f'}}>删除</a>
                </>
            ),
        }
    ];
    const [editData, setEditData] =useSetState({visible:false,detailData:{}});
    useEffect(() => {
        dispatch({type:SAGA_GETMENULIST});
    }, [])
    const aaa=(par:string,event:React.MouseEvent<HTMLDivElement, MouseEvent>)=>{
        event.persist()
        console.log('11', par,event)
    }
    const datas:LayoutTableProps={
        btnGrounp:[
           {
               title:'新增',
               iconClass:'add', 
               func:(e:React.MouseEvent<HTMLDivElement, MouseEvent>)=>handle(1),
           }
        ],
        iconGrounp:[
            {
                title:'刷新',
                func:(e:React.MouseEvent<HTMLDivElement, MouseEvent>)=>aaa('rr',e),
                icon:<SyncOutlined/>
            }
        ],
    }
    const handle=(state:number,detailData:any={})=>{
        if(state==1){ 
            setEditData({visible:true,detailData});
       }else if(state==2){
           
       }
    }
    return (
        <>
            <LayoutTableComponent {...datas}>
                <Table columns={columns} dataSource={getMenuList} loading={false}/>
                <Pagination total={10}   onChanges={(page:number, size:number)=>{}}/>
            </LayoutTableComponent>
            <MenuOption {...editData} onCancel={()=>setEditData({visible:false})} sucessCallback={()=>dispatch({type:SAGA_GETMENULIST})}/>
            {/* <div className='layout-table'>
                <div className='header-option'>
                    <div className='header-option-title'>查询表格</div>
                    <div className='header-option-func'>
                        <div className='option-btn'>
                            <Buttons title='新增'  iconClass='add'/>
                        </div>
                        <div className='option-icon'>
                             <Line/>
                            <div className='icon-grounp'>
                                <div className='update-data'>
                                    <Tooltip title='刷新'  placement="bottom" >
                                        <SyncOutlined />
                                    </Tooltip>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
               
                <Table columns={columns} dataSource={getMenuList} loading={false}/>
            </div> */}
        </>
    )
})

export default connect(({user}:reduceStoreType)=>({
    getMenuList:user.getMenuList
}))(Menu);

// vue+typescript/src/views/system/menu/index.vue
<template>
  <div class="com-page">
    <LayoutTable
      tableTitle="查询表格"
      :loading="loading"
      :tableProps="{
        columns,
        dataSource: menuData.list,
        rowKey: v => v.id
      }"
      :pagination="{
        total: menuData.total,
        current: params.page,
        pageSize: params.size,
        onChange: onPaginationChange
      }"
      :onRefresh="query"
    >
      <template #buttons>
        <a-button type="primary" @click="onCreate">
          <template #icon>
            <ComSvgIcon
              class="anticon add-button__icon"
              name="add"
            ></ComSvgIcon>
          </template>
          <span>新增</span>
        </a-button>
      </template>
      <template #index="{ index }">
        <span>
          {{ index + 1 }}
        </span>
      </template>
      <template #icon="{ text }">
        <span>
          {{ text || '/' }}
        </span>
      </template>
      <template #createTime="{ text }">
        <span>
          {{ $formatDateTime(text) }}
        </span>
      </template>
      <template #action="{ record }">
        <!-- <a-button type="link" @click="onUpdate(record)">编辑</a-button>
        <a-button type="link" @click="onDelete(record)">删除</a-button> -->
        <a @click="onUpdate(record)">编辑</a>
        <a-divider type="vertical" />
        <a class="danger" @click="onDelete(record)">删除</a>
      </template>
    </LayoutTable>
    <UpdateMenuModal
      v-model:visible="visible"
      :currentRow="currentRow"
      :menuCascaderOptions="menuTree"
      @create-success="onCreateSuccess"
      @update-success="onUpdateSuccess"
    ></UpdateMenuModal>
  </div>
</template>

<script lang="ts">
import {
  defineComponent,
  reactive,
  toRefs,
  // ref,
  createVNode
} from 'vue'
import { Modal, message } from 'ant-design-vue'
import { Canceler } from 'axios'
import { ExclamationCircleOutlined } from '@ant-design/icons-vue'
import userStore from '@/store/modules/user'
import LayoutTable from '@/components/layout-table'
import { getMenus, getMenuTree, deleteMenu } from './service'
import { useAsync } from '@/hooks'
import UpdateMenuModal from './update-menu-modal.vue'

type MenuItem = {
  id: number
  pid: number
  title: string
  url: string
  icon: string
  createTime: number
}

const columns = [
  {
    dataIndex: 'index',
    key: 'index',
    align: 'center',
    title: '序号',
    slots: { customRender: 'index' }
  },
  {
    dataIndex: 'id',
    key: 'id',
    align: 'center',
    title: 'id'
  },
  {
    dataIndex: 'pid',
    key: 'pid',
    align: 'center',
    title: 'pid'
  },
  {
    dataIndex: 'title',
    key: 'title',
    align: 'center',
    title: '名称'
  },
  {
    dataIndex: 'url',
    key: 'url',
    align: 'center',
    title: 'url'
  },
  {
    dataIndex: 'icon',
    key: 'icon',
    align: 'center',
    title: 'icon',
    slots: { customRender: 'icon' }
  },
  {
    dataIndex: 'createTime',
    key: 'createTime',
    align: 'center',
    title: '创建时间',
    slots: { customRender: 'createTime' }
  },
  {
    key: 'action',
    align: 'center',
    title: '操作',
    slots: { customRender: 'action' }
  }
]
export default defineComponent({
  name: 'MenuPage',
  components: {
    LayoutTable,
    UpdateMenuModal
  },
  setup() {
    const state = reactive({
      columns,
      params: {
        page: 1,
        size: 10
      },
      visible: false,
      currentRow: {}
    })

    let cancel: Canceler | null = null

    const { data: menuData, loading, run: query } = useAsync(
      () => {
        return getMenus(state.params)
      },
      {
        initialData: {
          list: [],
          total: 0
        }
      }
    )

    const { data: menuTree } = useAsync(
      () => {
        return getMenuTree()
      },
      {
        initialData: []
      }
    )

    function onSearch() {
      setTimeout(() => {
        query()
      }, 20)
    }

    function onCreate() {
      state.currentRow = {}
      state.visible = true
    }

    function onUpdate(row: MenuItem) {
      state.currentRow = row
      state.visible = true
    }

    function onDelete(row: MenuItem) {
      const modal = Modal.confirm({
        title: '温馨提示',
        content: '确定要删除吗',
        icon: createVNode(ExclamationCircleOutlined),
        onOk: async () => {
          try {
            await deleteMenu(row.id, c => (cancel = c))
            message.destroy()
            message.success('删除成功')
            query()
            userStore.getAccessMenus()
          } catch (err) {
            console.log(err)
          }
        },
        onCancel: () => {
          cancel && cancel()
          console.log('onCancel', modal)
        }
      })
    }

    function onPaginationChange(page: number, size: number) {
      state.params.page = page
      state.params.size = size
      query()
    }

    function onCreateSuccess() {
      state.params.page = 1
      query()
      userStore.getAccessMenus()
    }

    function onUpdateSuccess() {
      query()
      userStore.getAccessMenus()
    }

    return {
      ...toRefs(state),
      menuData,
      menuTree,
      loading,
      query,
      onSearch,
      onCreate,
      onUpdate,
      onDelete,
      onPaginationChange,
      onCreateSuccess,
      onUpdateSuccess
    }
  }
})
</script>

<style lang="less" scoped>
.danger {
  color: rgb(255, 77, 79);
}
.add-button__icon {
  font-size: 18px;
}
</style>
