// vue+typescript/src/components/layout-table/table-size.tsx
import { defineComponent } from 'vue'
import { ColumnHeightOutlined } from '@ant-design/icons-vue'

export type TableSizeType = 'middle' | 'large' | 'small'

export default defineComponent({
  name: 'TableSize',
  props: {
    onChange: {
      type: Function,
      default: () => {} // eslint-disable-line
    }
  },
  render() {
    const menu = (
      <a-menu onClick={this.onChange} selectable defaultSelectedKeys={['middle']}>
        <a-menu-item key="middle">默认</a-menu-item>
        <a-menu-item key="large">松散</a-menu-item>
        <a-menu-item key="small">紧凑</a-menu-item>
      </a-menu>
    )
    return (
      <a-tooltip title="密度" placement="left">
        <a-dropdown overlay={menu} placement="bottomCenter">
          <ColumnHeightOutlined />
        </a-dropdown>
      </a-tooltip>
    )
  }
})

// react/src/components/layout/layoutTable/tableSize.jsx
import React, { memo } from 'react'
import { ColumnHeightOutlined } from '@ant-design/icons';
import { Tooltip, Dropdown, Menu } from 'antd'

const TableSize = memo(function TableSize({ tableSize, className }) {
  const handleClick = (e) => tableSize(e.key);

  const menu = (
    <Menu onClick={handleClick} selectable defaultSelectedKeys={['middle']}>
      <Menu.Item key='middle'>默认</Menu.Item>
      <Menu.Item key='large'>松散</Menu.Item>
      <Menu.Item key='small'>紧凑</Menu.Item>
    </Menu>
  );

  return (
    <>
      <Tooltip title='密度' placement="left">
        <Dropdown overlay={menu} placement="bottomCenter">
          <ColumnHeightOutlined className={className} />
        </Dropdown>
      </Tooltip>
    </>
  )
})
export default TableSize
