// react/src/pages/drag/baseCompents/News/index.js
import React, { memo,useState,useEffect } from 'react'
import { NotificationOutlined } from '@ant-design/icons';
import PropTypes from 'prop-types'

const NewCompent = memo(function NewCompent(props) {

  return (
    <div style={{fontSize:'16px',fontWeight:'bold'}}>
      <NotificationOutlined />
      <span style={{padding:"0 10px"}}>ant-simple-pro上线了！</span>
    </div>
  )
})

NewCompent.propTypes = {

}

export default NewCompent;

// vue+typescript/src/views/drag/templates/news.vue
<template>
  <div class="font-size-16 font-weight-bold">
    <NotificationOutlined />
    <span class="p10">ant-simple-pro上线了！</span>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { NotificationOutlined } from '@ant-design/icons-vue'
export default defineComponent({
  name: 'TempNews',
  components: {
    NotificationOutlined
  }
})
</script>
